language: go
go:
    - 1.6
    - tip
install:
    - go get -u -t -v ./...
    - go get github.com/golang/lint/golint golang.org/x/tools/cmd/goimports github.com/onsi/ginkgo/ginkgo
script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint ./...
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
after_success:
    - bash <(curl -s https://codecov.io/bash) -f *.coverprofile
